### ISSUE TITLE
How to use in the browser/frontend?

### ISSUE THREAD

**Issue by Catsvilles** [audiojs/audio-buffer-utils#15]
Sorry, I am not very experienced with node.js and I figured since this is about Web Audio API audiobuffers it should be easy to use this package in the browser? Are there any examples with at least short explanations on how to add the script and start using it? For now, I get this error: 

> Uncaught ReferenceError: require is not defined

Thanks! :)

**Comment by dy** [comment]
Hey.
I'd recommend to rely on standard web-audio-api for now.
This is not supported for now and likely not going to be in the future, because there's a replacement coming.
